// Notation characters A, B, C, D, E, F, G are not configurable.

// Notation digits 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 as used in brackets
// and for octave numbers are also not configurable.

module.exports = {
  CHAR_OCTAVE_MARK: "o",
  CHAR_OCTAVE_UP: "+",
  CHAR_OCTAVE_DOWN: "-",

  CHAR_SHARP: "#",
  CHAR_FLAT: "b",
  CHAR_PYTHAG_ON: "p",
  CHAR_PYTHAG_OFF: "d",
  CHAR_MERCATOR_ON: "m",
  CHAR_MERCATOR_OFF: "w",
  CHAR_SMALL_ON: "s",
  CHAR_SMALL_OFF: "r",
  CHAR_TINY_ON: "t",
  CHAR_TINY_OFF: "y",

  CHAR_SYNTONIC_ON: "'",
  CHAR_SYNTONIC_OFF: ".",

  CHAR_COMMA_DIVIDE: "/",
  CHAR_COMMA_POWER: "^",

  BRACKET_LEFT_STANDARD: "(",
  BRACKET_RIGHT_STANDARD: ")",
  BRACKET_LEFT_COMMA: "[",
  BRACKET_RIGHT_COMMA: "]",

  BRACKET_ALLOWED_CHARS: "[](){}<>",

  ERROR_TEXT: "ERR",
  ERROR_MAX_CHARS: 2,
  MAX_DIGITS_UNSPLIT_HIGHER_PRIMES: 3,
  MAX_ERROR_DIGITS_2_OCTAVE: 15,
  MAX_OVERFLOW_DIGITS_2_OCTAVE: 6,
  MAX_ERROR_DIGITS_3_DIATONIC: 15,
  MAX_ERROR_DIGITS_3_SHARPS_FLATS: 15,
  MAX_OVERFLOW_DIGITS_3_SHARPS_FLATS: 6,
  MAX_REPEATS_3_SHARPS_FLATS: 4,
  MAX_ERROR_DIGITS_5_SYNTONIC_COMMA: 15,
  MAX_OVERFLOW_DIGITS_5_SYNTONIC_COMMA: 6,
  MAX_REPEATS_5_SYNTONIC_COMMA: 4,

  DUMMY: "DUMMY"
}
