// var ji = require('ji-rcn')           // via npm
var ji = require('../src/index.js')       // locally
var Jinote = ji.jinote
var jn = null
var peo = null

console.log("")
console.log("Example of newly created Jinote:")
console.log("`new Jinote(7, 5)`")
console.log("")
console.log(new Jinote(7, 5))
console.log("")
console.log("")

console.log("")
console.log("Example of Jinote with cached calculations:")
console.log("`new Jinote(7, 5)`")
console.log("")
jn = new Jinote(7, 5)
console.log(jn.getNotation())
console.log("")
console.log(jn)
console.log("")
console.log("")

console.log("")
console.log("Example of more complex Jinote:")
console.log("`new Jinote(31031000, 65537)`")
console.log("")
jn = new Jinote(31031000, 65537)
console.log(jn.getNotation())
console.log("")
console.log(jn)
console.log("")
console.log("")

console.log("")
console.log("Example of DR algorithm:")
console.log("`new Jinote(\"13/8\", \"DR\")`")
console.log("")
jn = new Jinote("13/8", "DR")
console.log(jn.getNotation())
console.log("")
console.log(jn)
console.log("")
console.log("")

console.log("")
console.log("Example of KG2 algorithm:")
console.log("`new Jinote(\"13/8\", \"KG2\")`")
console.log("")
jn = new Jinote("13/8", "KG2")
console.log(jn.getNotation())
console.log("")
console.log(jn)
console.log("")
console.log("")

console.log("")
console.log("Example of getting a comma:")
console.log("`Jinote.getComma(7)`")
console.log("")
console.log(Jinote.getComma(7))
console.log("")
console.log("")

console.log("")
console.log("Example of parsing notation text:")
console.log("`Jinote.parseNotation(\"D'[7]6\")`")
console.log("")
peo = Jinote.parseNotation("D'[7]6")
console.log(peo)
console.log("")
console.log(peo.getText())
console.log("")
console.log("")

console.log("")
console.log("Creation of Jinote on same notation text:")
console.log("`new Jinote(\"D'[7]6\")`")
console.log("")
jn = new Jinote("D'[7]6")
console.log(jn)
console.log("")
console.log(jn.getFraction())
console.log("")
console.log("")

for (var i=256; i<=275; i++) {
  var jn = new Jinote(i, 256)
  console.log(`${i}/256 maps to ${jn.getPitch()}`)
}
