var Peo = require('peo')

var result = {
  OVERFLOW_TEXT: "LOTS",

  PEO_2_OCTAVE: new Peo(2),
  PEO_3_DIATONIC_F: new Peo(4, 3),
  PEO_3_DIATONIC_C: new Peo(),
  PEO_3_DIATONIC_G: new Peo(3, 2),
  PEO_3_DIATONIC_D: new Peo(9, 8),
  PEO_3_DIATONIC_A: new Peo(27, 16),
  PEO_3_DIATONIC_E: new Peo(81, 64),
  PEO_3_DIATONIC_B: new Peo(243, 128),
  PEO_3_SHARP: new Peo({3:7, 2:-11}),

  NAME_2_OCTAVE: "o",
  NAME_3_SHARP: "#",
  NAME_3_FLAT: "b",
  NAME_5_SYNTONIC_COMMA_ADD: "'",
  NAME_5_SYNTONIC_COMMA_REMOVE: ".",

  BRACKET_2_OCTAVE_LEFT: "(",
  SYMBOL_2_OCTAVE_UP: "+",
  SYMBOL_2_OCTAVE_DOWN: "-",
  BRACKET_2_OCTAVE_RIGHT: ")",
  BRACKET_3_SHARP_FLAT_LEFT: "(",
  BRACKET_3_SHARP_FLAT_RIGHT: ")",
  BRACKET_5_SYNTONIC_LEFT: "(",
  BRACKET_5_SYNTONIC_RIGHT: ")",
  BRACKET_HIGHER_COMMA_LEFT: "[",
  SYMBOL_HIGHER_COMMA_MID: "/",
  SYMBOL_HIGHER_COMMA_POW: "^",
  BRACKET_HIGHER_COMMA_RIGHT: "]",

  MAX_ERROR_DIGITS_2_OCTAVE: 15,
  MAX_OVERFLOW_DIGITS_2_OCTAVE: 6,
  ERROR_TEXT_2_OCTAVE: "o.Err",

  MAX_ERROR_DIGITS_3_DIATONIC: 15,
  ERROR_TEXT_3_DIATONIC_NA: "Na",
  ERROR_TEXT_3_DIATONIC_LO: "Lo",
  ERROR_TEXT_3_DIATONIC_HI: "Hi",

  MAX_ERROR_DIGITS_3_SHARPS_FLATS: 15,
  MAX_OVERFLOW_DIGITS_3_SHARPS_FLATS: 6,
  MAX_REPEATS_3_SHARPS_FLATS: 4,
  ERROR_TEXT_3_SHARPS_FLATS: "N",

  MAX_ERROR_DIGITS_5_SYNTONIC_COMMA: 15,
  MAX_OVERFLOW_DIGITS_5_SYNTONIC_COMMA: 6,
  MAX_REPEATS_5_SYNTONIC_COMMA: 4,
  ERROR_TEXT_5_SYNTONIC_COMMA: "5ERR",

  MAX_DIGITS_UNSPLIT_HIGHER_PRIMES: 3,

  DUMMY: "DUMMY"
}

module.exports = result
